print("i will now count my chicken:")
print("hence",25+30/6)
print("roosters",25-30*3%4)
print("Now i will count the eggs:")
print(3+2+1-5+4%2-1/4+7)
print("is it true that 5-2<3+7?")
print(3+2<5-7)
print("what is 3+2?",3+2)
print("what is 5-7?",5-7)
print("oh,that's why it is false.")
print("how about some more.")
print("is it greater?",5>-2)
print("is it greater or equal?",5>=-2)
print("is it less or equal?",5<=-2)
